const Tesseract = require('tesseract.js');

exports.extractReceiptData = async (imagePath) => {
    try {
        // Run OCR on the receipt
        const result = await Tesseract.recognize(imagePath, 'eng');
        const text = result.data.text;
        
        // Simulating the PDF feature: Autogenerated with amount, date, description, expense lines, expense type, name of restaurant
        // Industry note: Real enterprise uses ML/Vision parsing, but we utilize regex and heuristics on Tesseract text
        
        const lines = text.split('\n').filter(l => l.trim().length > 2);
        
        // Try extracting an amount pattern (e.g. $12.99 or 450)
        const amountMatch = text.match(/\$?\d+(\.\d{2})?/);
        const inferredAmount = amountMatch ? parseFloat(amountMatch[0].replace('$', '')) : 0;
        
        return {
            amount: inferredAmount || 0,
            date: new Date().toISOString().split('T')[0], // Mocks today's date if not reliably found
            description: "Auto-scanned expense from OCR",
            expenseType: "Meals / Travel",
            restaurantName: lines[0] || "Unknown Vendor", // Heuristic: Assume first line is vendor logo/name
            expenseLines: lines.slice(1, 4), // Next few lines normally hold items
            rawOcrText: text
        };
    } catch (error) {
        console.error("OCR API Engine Error:", error.message);
        throw error;
    }
};
